production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>

development:
  clients:
    default:
      database: connector_development
      hosts:
        - localhost:27017
test:
  clients:
    default:
      database: connector_test
      hosts:
        - localhost:27017
      options:
        read: primary
        # In the test environment we lower the retries and retry interval to
        # low amounts for fast failures.
        max_retries: 1
        retry_interval: 0
